### ISSUE TITLE
SVG image format is not supported as website logo

### ISSUE THREAD

**Issue by Oliver-Loeffler** [mkirste/io200#1]
Hi,

well IO200 makes a great impression and I am hoping that once in a while this could replace my old Koken instance.
Playing around with IO200 I've found, that one cannot easily use SVG images as a page logo. The current version is restricted to PNG and JPG.

## Observed behavior:

* admin page
* Settings
* Theme -> Logo
     * It is impossible to select a SVG file as a logo

## Expected behavior
* The function behind `admin page/Settings/Theme/Logo` supports using SVG graphics (besides PNG or JPG).

Is there any chance you could get this working?

Thanks!

**Comment by mkirste** [comment]
Hi Oliver,
thanks for your suggestion. The latest version (2.9.1) adds support for svg logos ([https://www.io200.com/changelog](https://www.io200.com/changelog)).
Best, Michael

**Comment by Oliver-Loeffler** [comment]
Thanks, that was much quicker than expected.
