### ISSUE TITLE
Menu editor does not support case-sensitive URLs for links, instead it turns all lower case and breaks links.

### ISSUE THREAD

**Issue by Oliver-Loeffler** [mkirste/io200#2]
The website menu editor allows to add basic raw links for navigation.

This is achieved by:
* navigate to admin area
* navigate to menu editor
* select primary navigation
* click on `+ New Link`
* select `none (raw link)` from templates

Here one would expect that the given URL is not modified.
Unfortunately there are case-sensitive URLs in the web.

An example is `https://oliver-loeffler.github.io/FXFileChooser/`. When entered as a link, it is modified to: `https://oliver-loeffler.github.io/fxfilechooser/` and this version does not exist.

## Observed behavior:
* URLs are turned all lower case

## Expected behavior:
* case of letters in provided URLs must not be changed

## Note
* Changing the URL in the database accordingly immediately yields the desired behavior.

**Comment by mkirste** [comment]
Issue fixed. External links will no longer be turned to lower case. Fix will be released with next version.
